import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">About page</h1>
      <Link href="/">
        <a>&larr; Go Back</a>
      </Link>
    </div>
  );
};

export default About;
