import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const About: NextPage = () => {
  return (
    <div className="grid min-h-screen place-content-center">
      <Head>
        <title>About | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mb-4 text-5xl font-bold">About page</h1>
      <nav>
        <Link href="/">
          <a className="underline underline-offset-4">
            &larr; Return to homepage
          </a>
        </Link>
      </nav>
    </div>
  );
};

export default About;
