import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="grid min-h-screen place-content-center">
      <Head>
        <title>Home | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mb-4 text-5xl font-bold">Homepage</h1>
      <nav>
        <Link href="/about">
          <a className="underline underline-offset-4">Visit the about page</a>
        </Link>
      </nav>
    </div>
  );
};

export default Home;
