import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Homepage</h1>
      <nav>
        <Link href="/about">
          <a>About page</a>
        </Link>
      </nav>
      <p>The above link ensures e2e tests are working correctly!</p>
    </div>
  );
};

export default Home;
